# Builds an image and push it to registry.
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-image
spec:
  taskSpec:
    steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.9.0
      args:
      - --destination=${HUB_URL}:443/hello
      - --context=/workspace/workspace
      volumeMounts:
      - name: source
        mountPath: /workspace/workspace
    volumes:
    - name: source
      configMap:
        name: source
